In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

listings = pd.read_csv('../02_Data/processed/listings_clean.csv')
reviews = pd.read_csv('../02_Data/processed/reviews_clean.csv', parse_dates=['date'])
calendar = pd.read_csv('../02_Data/processed/calendar_clean.csv', parse_dates=['date'])

In [7]:
sh_overall = listings.groupby('host_is_superhost').agg(
    listings = ('id','count'),
    median_price = ('price', 'median'),
    pct_entire_home=('room_type', lambda s: round((s=='Entire home/apt').mean()*100,1)),
    median_reviews=('number_of_reviews', 'median')
).round(1)

display(sh_overall)

within_nb = listings.groupby(['neighbourhood', 'host_is_superhost'])['price'].median().unstack()
within_nb['diff'] = within_nb[True] - within_nb[False]
within_nb = within_nb.dropna().sort_values('diff', ascending=False)

print(f"\n Within-Neighbourhood Superhost Premium (median €)")
display(within_nb.head(10))
print(f"\nMedian premium across neighbourhoods: €{within_nb['diff'].median():.0f}")

# Similarly control for room type
within_rt = listings.groupby(['room_type', 'host_is_superhost'])['price'].median().unstack()
print("\n Within-Room-Type Superhost Premium")
display(within_rt)

# Missing status check
print(f"\nListings with missing host status: {listings['host_is_superhost'].isna().sum()}")

                   listings  median_price  pct_entire_home  median_reviews
host_is_superhost
False                 11274         161.0             67.0             4.0
True                   3932         220.0             83.8            58.0

 Within-Neighbourhood Superhost Premium (median €)

host_is_superhost                 False     True     diff
neighbourhood
la Font d'en Fargues              45.77  1409.33  1363.56
el Putxet i el Farró             120.73   263.67   142.94
Sant Andreu                       63.73   199.00   135.27
la Maternitat i Sant Ramon       115.00   234.12   119.12
l'Antiga Esquerra de l'Eixample  157.22   273.88   116.66
la Bordeta                       108.00   212.00   104.00
el Congrés i els Indians          73.50   171.43    97.93
la Sagrera                        80.00   170.01    90.01
el Guinardó                      103.85   191.39    87.54
Sant Gervasi - Galvany           146.07   231.50    85.43

Median premium across neighbourhoods: €22

 Within-Room-Type Superhost Premium

host_is_superhost   False   True
room_type
Entire home/apt    210.00  241.93
Hotel room         200.35  189.50
Private room        61.62   76.08
Shared room         46.50   46.00

Listings with missing host status: 87